name: 📋 Benchmark

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

concurrency:
  group: benchmark-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Performance Test
    runs-on: ubuntu-latest

    # This is really expensive, so we only want to run it when we need to.
    if: contains(github.event.pull_request.labels.*.name, 'benchmark-needed')

    strategy:
      matrix:
        configuration:
          - control # Without extension enabled.
          - enabled # Extension enabled but no probing.
          - probing # Extension enabled with probing from bpftrace.

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v4

      - name: 📁 Init
        run: |
          # Create benchmark testing results directory.
          sudo mkdir -p /tmp/output
          sudo chmod 777  /tmp/output

          # Copy the env file for the current configuration to the root of the repository, so that it gets picked up by docker compose.
          cp .github/workflows/benchmark/${{ matrix.configuration }}/.env .env

      - name: 📦 Up
        run: |
          docker compose up -d --wait --build

      - name: 🧪 K6
        run: |
          docker run --rm \
                     --network=host \
                     -v /tmp/output:/results \
                     -i docker.io/grafana/k6 run - --summary-export=/results/report.json --vus 2 --duration 30s < .github/workflows/benchmark/basic.js

      - name: 📋 Save Logs (Debugging)
        if: always()
        run: |
          docker compose logs nginx > /tmp/output/nginx.log
          docker compose logs php-fpm > /tmp/output/php-fpm.log

      - name: 📋 Archive Output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.configuration }}
          path: |
            /tmp/output

  results:
    name: Compare Results
    runs-on: ubuntu-latest
    needs: test

    # This is really expensive, so we only want to run it when we need to.
    if: contains(github.event.pull_request.labels.*.name, 'benchmark-needed')

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: 📋 Review Test Results
        run: |
          go run .github/workflows/benchmark/results.go

      - name: 📋 Post Test Results to Summary
        if: always()
        run: cat summary.md >> $GITHUB_STEP_SUMMARY
