name: 📋 Quality

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

concurrency:
  group: quality-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v4

      - name: 📦 Build devcontainer
        run: |
          docker build -t localhost/devcontainer .devcontainer

      - name: 📋 Validate
        run: |
          docker run --rm -v $(pwd):$(pwd) -w $(pwd) localhost/devcontainer mise validate

      - name: 📋 Clippy
        run: |
          docker run --rm -v $(pwd):$(pwd) -w $(pwd) localhost/devcontainer mise clippy

      - name: 📋 Format
        run: |
          docker run --rm -v $(pwd):$(pwd) -w $(pwd) localhost/devcontainer mise lint
